# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    twig.output_html:
        class: Twig\OutputHtml
        tags:
            - { name: twig.extension }

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.doctrine.user_photo_upload_listener:
        class: AppBundle\Doctrine\UserPhotoUploadListener
        arguments: ['@app.file_uploader', '%user_photo_dir%']
        tags:
            - { name: doctrine.event_subscriber }

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.security.login_facebook:
        class: League\OAuth2\Client\Provider\Facebook
        arguments:
            -
                clientId: 272372656515794
                clientSecret: afeb75fcb89b2ca310ae61ce209d2b12
                graphApiVersion: v2.8
                redirectUri: "http://localhost:8000/login/facebook/check"

    app.security.login_facebook_authenticator:
        class: AppBundle\Security\LoginFacebookAuthenticator
        autowire: true

    app.validator.username_exists:
        class: AppBundle\Validator\Constraints\UsernameExistsValidator
        autowire: true
        tags:
            - { name: validator.constraint_validator }

    app.send_mail:
        class: AppBundle\Service\SendMail
        arguments: ['@swiftmailer.mailer', '@twig', '@doctrine.orm.entity_manager', '%admin_mail%']

    app.security.reset_password:
        class: AppBundle\Service\ResetPassword
        autowire: true

    app.file_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ['%user_photo_dir%']

    app.show_articles:
        class: AppBundle\Service\ShowArticles
        arguments: ['@doctrine.orm.entity_manager']

    app.show_comments:
        class: AppBundle\Service\ShowComments
        arguments: ['@doctrine.orm.entity_manager']

    app.manager.comments_manager:
        class: AppBundle\Manager\CommentsManager
        autowire: true

    app.manager.articles_manager:
        class: AppBundle\Manager\ArticlesManager
        autowire: true